### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mee7ya** [mee7ya/airflow-providers-mattermost#2]
- [x] Support [Attachments](https://developers.mattermost.com/integrate/reference/message-attachments/)
- [x] Single ``compose.yaml`` with Airflow + Mattermost for development
- [x] Check actions for 3.10 - 3.12 Python
- [x] Build docs on release + correct docs tags
